version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

